-- MySQL for Mac
--
-- Host: localhost    Database: Stocks
-- ------------------------------------------------------
-- Server version	8.0.17

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `my_capital`
--

DROP TABLE IF EXISTS `my_capital`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `my_capital` (
  `capital` FLOAT(30,2) NOT NULL,
  `money_lock` FLOAT(30,2) DEFAULT NULL,
  `money_rest` FLOAT(30,2) DEFAULT NULL,
  `deal_action` VARCHAR(45) DEFAULT NULL,
  `stock_code` VARCHAR(45) DEFAULT NULL,
  `deal_price` FLOAT(30,2) DEFAULT NULL,
  `stock_vol` INT(20) DEFAULT NULL,
  `profit` FLOAT(30,2) DEFAULT NULL,
  `profit_rate` FLOAT(20,2) DEFAULT NULL,
  `bz` VARCHAR(45) DEFAULT NULL,
	`state_dt` VARCHAR(45) DEFAULT NULL,
  `seq` INT(11) NOT NULL AUTO_INCREMENT,
  `score` FLOAT(20,6) DEFAULT NULL,
  PRIMARY KEY (`seq`)
) ENGINE=InnoDB AUTO_INCREMENT=181 DEFAULT CHARSET=gbk;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `my_capital`
--

LOCK TABLES `my_capital` WRITE;
/*!40000 ALTER TABLE `my_capital` DISABLE KEYS */;
INSERT INTO `my_capital` VALUES (1000000.00,0.00,1000000.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL);
/*!40000 ALTER TABLE `my_capital` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-08-21 10:24:19